services:
  bucstop:
    build:
      context: ./Bucstop WebApp/BucStop
      dockerfile: Dockerfile
    container_name: bucstop
    ports:
      - "8080:80"
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containers}
      - GIT_COMMIT_HASH=${GIT_COMMIT:-unknown}
    depends_on:
      - api-gateway
    volumes:
      - snapshots-data:/app/Snapshots
      - logs-data:/app/Logs
      - game-data:/app/GameData

  api-gateway:
    build:
      context: ./Team-3-BucStop_APIGateway/APIGateway
      dockerfile: Dockerfile
    container_name: api-gateway
    ports:
      - "8081:80" # Expose API Gateway on localhost:8081
    networks:
      - bucstop-network
    environment:
      - DOTNET_ENVIRONMENT=${env:-containersLocal}
    depends_on:
      - snake
      - pong
      - tetris

  snake:
    build:
      context: ./Team-3-BucStop_Snake/Snake
      dockerfile: Dockerfile
    container_name: game-snake
    environment:
      - DOTNET_ENVIRONMENT=${env:-containersLocal}
    ports:
      - "8082:80" # Expose Snake microservice on localhost:8082
    networks:
      - bucstop-network

  pong:
    build:
      context: ./Team-3-BucStop_Pong/Pong
      dockerfile: Dockerfile
    container_name: game-pong
    environment:
      - DOTNET_ENVIRONMENT=${env:-containersLocal}
    ports:
      - "8083:80" # Expose Pong microservice on localhost:8083
    networks:
      - bucstop-network

  tetris:
    build:
      context: ./Team-3-BucStop_Tetris/Tetris
      dockerfile: Dockerfile
    container_name: game-tetris
    environment:
      - DOTNET_ENVIRONMENT=${env:-containersLocal}
    ports:
      - "8084:80" # Expose Tetris microservice on localhost:8084
    networks:
      - bucstop-network
      
  buckart:
      build:
        context: ./Team-3-BucStop_BucKart/BucKart
        dockerfile: Dockerfile
      container_name: game-buckart
      environment:
        - DOTNET_ENVIRONMENT=${env:-containersLocal}
      ports:
        - "8085:80" # Expose BucKart microservice on localhost:8085
      networks:
        - bucstop-network

  submission-gateway:
    build:
      context: ./Team-3-BucStop_SubmissionGateway/SubmissionGateway
      dockerfile: Dockerfile
    container_name: submission-gateway
    environment:
      - DOTNET_ENVIRONMENT=${env:-containersLocal}
      - ASPNETCORE_URLS=http://+:80
    ports:
      - "8086:80" # Expose Submission Gateway on localhost:8086
    networks:
      - bucstop-network
    volumes:
      # Store submissions data locally in the project folder
      - ./Team-3-BucStop_SubmissionGateway/SubmissionGateway/Data:/app/Data
      # Store uploaded files locally in the project folder
      - ./Team-3-BucStop_SubmissionGateway/SubmissionGateway/Uploads:/app/Uploads

networks:
  bucstop-network:
    driver: bridge

volumes:
  snapshots-data:
    driver: local
  logs-data:
    driver: local
  game-data:
    driver: local
