name: Swagger Editor Validate

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'

jobs:
  swagger-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate OpenAPI definition
        uses: mbowman100/swagger-validator-action@master
        with:
          files: 'Bucstop\ WebApp/BucStop/openapi.json'

        

