name: Swagger Editor Validate

on:
  push:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'
  pull_request:
    paths:
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.json'

jobs:
  swagger-validation:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install swagger-cli
        run: npm install -g @apidevtools/swagger-cli

      - name: Validate OpenAPI definition
        run: swagger-cli validate 'Buckstop WebApp/BucStop/openapi.json'

